name: Build Info Update

on:
  push:
    branches: [ main ]  # Запуск при push в main (можно изменить на другие ветки)

jobs:
  build_info:
    runs-on: ubuntu-latest  # ОС для выполнения (Linux)
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4  # Обновил до v4 для актуальности

      - name: Установка Python
        uses: actions/setup-python@v5  # Обновил до v5
        with:
          python-version: '3.12'  # Версия Python (можно изменить)

      - name: Обновление файла build_info.txt
        run: python PJ11_gitinfo_08.py  # Замените на имя вашего файла скрипта

      - name: Сохранение изменений
        run: |
          git config user.name "CI Bot"
          git config user.email "ci@example.com"
          git add build_info.txt
          git commit -m "Автоматическое обновление build_info.txt [skip ci]"  # [skip ci] чтобы избежать цикла
          git push